vich_uploader:
    db_driver: orm

    mappings:
        articles_image:  
            upload_destination: '%kernel.project_dir%/public/img/articles/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer