vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: 
            upload_destination: '%kernel.project_dir%/public/img/articles/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer